org: wordrew
app: twitter-mock
service: twitter-mock-api
# useDotenv: true

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  lambdaHashingVersion: "20201221"

functions:
  twitter-mock-API:
    handler: handler.handler
    events:
      - http: ANY /{proxy+} # do not change
      - http: ANY /
   
